# LLM AUGMENTATION UTILIZANDO LLAMA
#### Nessa etapa 2, vamos aplicar o llama-3-3-70b para parafrasear as estruturas dos tipos menos frequentes, aumentando e padronizando o dataset.

In [2]:
import pandas as pd
from pipeline.preprocessor import Preprocessor
from pipeline.llm_augmenter import LlamaAugmenter

In [3]:
df = pd.read_csv("data/raw_datasets/mbti_1.csv")

In [4]:
df.head()

   type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [5]:
import pandas as pd

df_bruto = pd.read_csv("data/raw_datasets/mbti_1.csv")

# (Opcional) Uma limpezinha bem leve apenas de URLs antes da IA, se quiser ajudar o Llama
preprocessor_leve = Preprocessor(texts_column='posts')
df_bruto = preprocessor_leve.remove_urls(df_bruto)

# 2. Instancia e roda o LlamaAugmenter PRIMEIRO (no texto com gramática)
augmenter = LlamaAugmenter(texts_column='posts', label_column='type')
df_aumentado_bruto = augmenter.augment_minority_classes(df_bruto)

# 3. AGORA SIM: Limpeza Pesada em TUDO (textos originais + gerados pela IA)
print("Iniciando a limpeza pesada (NLP)...")
preprocessor_pesado = Preprocessor(texts_column='posts')
df_final_limpo = preprocessor_pesado.preprocess_complete(df_aumentado_bruto)

# Salva o resultado final pronto para o Word2Vec
df_final_limpo.head()

Iniciando augmentation local com llama3...
Gerado sucesso: ENTP
Gerado sucesso: ENTJ
Gerado sucesso: ENFJ
Gerado sucesso: ENTJ
Gerado sucesso: ENTJ
Gerado sucesso: ENFP
Gerado sucesso: ISFP
Gerado sucesso: ENFJ

KeyboardInterrupt:

In [21]:
df_aumentado.head()

   type                                              posts  is_synthetic
0  INFJ  moment sportscenter top ten play prankswhat ha...         False
1  ENTP  im finding lack post alarmingsex boring positi...         False
2  INTP  good one _____ course say know thats blessing ...         False
3  INTJ  dear enjoyed conversation day esoteric gabbing...         False
4  ENTJ  youre firedthats another silly misconception a...         False