# LLM AUGMENTATION UTILIZANDO LLAMA
#### Nessa etapa 2, vamos aplicar o llama-3-3-70b para parafrasear as estruturas dos tipos menos frequentes, aumentando e padronizando o dataset.

In [2]:
!pip install pandas nltk ollama

Requirement already satisfied: pandas in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (2.2.3)
Requirement already satisfied: nltk in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (3.9.1)
Requirement already satisfied: ollama in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (0.6.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pandas) (2025.1)
Requirement already satisfied: click in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from nltk) (4.67.1)
Requirement already satisfied: httpx>=0.27 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from ollama) (2.13.4)
Requirement already satisfied: anyio in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from httpx>=0.27->ollama) (4.12.1)
Requirement already satisfied: certifi in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from httpx>=0.27->ollama) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from httpx>=0.27->ollama) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pydantic>=2.9->ollama) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pydantic>=2.9->ollama) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pydantic>=2.9->ollama) (0.4.2)
Requirement already satisfied: six>=1.5 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from anyio->httpx>=0.27->ollama) (1.2.2)
Requirement already satisfied: colorama in c:\users\yasmi\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from click->nltk) (0.4.6)

In [2]:
import pandas as pd
from pipeline.preprocessor import Preprocessor
from pipeline.llm_augmenter import QwenAugmenter

In [3]:
df = pd.read_csv("data/raw_datasets/mbti_1.csv")

In [4]:
df.head()

   type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [5]:
pre = Preprocessor(texts_column='posts')

In [6]:
df_limpo_url = pre.remove_urls(df)
df_limpo = pre.remove_html(df_limpo_url)

In [7]:
df.head()

   type                                              posts
0  INFJ  '||||||enfp and intj moments    sportscenter n...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   |||Of course, to which I sa...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [8]:
df_limpo.head()

   type                                              posts
0  INFJ  '||||||enfp and intj moments    sportscenter n...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   |||Of course, to which I sa...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [9]:

# 2. Instancia e roda o LlamaAugmenter PRIMEIRO (no texto com gramática)
augmenter = QwenAugmenter(texts_column='posts', label_column='type')
df_aumentado_bruto = augmenter.augment_minority_classes(df)

Verificando/Baixando o modelo 'qwen2.5'... Isso pode demorar na 1ª vez se você ainda não baixou.
Iniciando augmentation local com qwen2.5...
Carregando checkpoint salvo em 'data/augmentation_checkpoint.csv'...
330 textos já processados encontrados. Retomando de onde parou...
Gerado sucesso: ENFP (index original: 1037)
Gerado sucesso: ENFP (index original: 1039)
Gerado sucesso: ENFP (index original: 1047)
Gerado sucesso: ENTP (index original: 1048)
Gerado sucesso: ISTJ (index original: 1049)
Gerado sucesso: ISFP (index original: 1050)
Gerado sucesso: ISFJ (index original: 1052)
Gerado sucesso: ENFJ (index original: 1053)
Gerado sucesso: ISTP (index original: 1055)
Gerado sucesso: ENTP (index original: 1057)
Gerado sucesso: ENTP (index original: 1058)
Gerado sucesso: ISTP (index original: 1059)
Gerado sucesso: ISFP (index original: 1060)
Gerado sucesso: ISFJ (index original: 1061)
Gerado sucesso: ISFP (index original: 1062)
Gerado sucesso: ISTJ (index original: 1063)
Gerado sucesso: ENFP (index original: 1066)
Gerado sucesso: ISFP (index original: 1067)
Gerado sucesso: ISTP (index original: 1070)
Gerado sucesso: ENFP (index original: 1075)
Gerado sucesso: ENFJ (index original: 1077)
Gerado sucesso: ENTP (index original: 1082)
Gerado sucesso: ENTP (index original: 1083)
Gerado sucesso: ISFP (index original: 1088)
Gerado sucesso: ISTJ (index original: 1089)
Gerado sucesso: ENFP (index original: 1090)
Gerado sucesso: ENTP (index original: 1092)
Gerado sucesso: ENFJ (index original: 1093)
Gerado sucesso: ISTP (index original: 1103)
Gerado sucesso: ESTJ (index original: 1112)
Gerado sucesso: ENTP (index original: 1113)
Gerado sucesso: ENTJ (index original: 1115)
Gerado sucesso: ISTP (index original: 1118)
Gerado sucesso: ISTP (index original: 1119)
Gerado sucesso: ENTP (index original: 1120)
Gerado sucesso: ENFP (index original: 1123)
Gerado sucesso: ISFJ (index original: 1127)
Gerado sucesso: ISTJ (index original: 1128)
Gerado sucesso: ENTP (index original: 1133)
Gerado sucesso: ESFP (index original: 1134)
Gerado sucesso: ISFP (index original: 1139)
Gerado sucesso: ISTJ (index original: 1141)
Gerado sucesso: ENTP (index original: 1144)
Gerado sucesso: ENFP (index original: 1148)
Gerado sucesso: ISFJ (index original: 1154)
Gerado sucesso: ISFJ (index original: 1155)
Gerado sucesso: ENFP (index original: 1159)
Gerado sucesso: ISFP (index original: 1160)
Gerado sucesso: ENTJ (index original: 1161)
Gerado sucesso: ENTP (index original: 1163)
Gerado sucesso: ISTJ (index original: 1166)
Gerado sucesso: ISTP (index original: 1172)
Gerado sucesso: ENFP (index original: 1173)
Gerado sucesso: ISFP (index original: 1176)
Gerado sucesso: ENTP (index original: 1177)
Gerado sucesso: ENTP (index original: 1181)
Gerado sucesso: ISFP (index original: 1184)
Gerado sucesso: ENFP (index original: 1185)
Gerado sucesso: ENFP (index original: 1187)
Gerado sucesso: ESTP (index original: 1192)
Gerado sucesso: ENTP (index original: 1199)
Gerado sucesso: ISTJ (index original: 1201)
Gerado sucesso: ENFP (index original: 1203)
Gerado sucesso: ENTP (index original: 1204)
Gerado sucesso: ISTJ (index original: 1206)
Gerado sucesso: ESTP (index original: 1207)
Gerado sucesso: ENTP (index original: 1209)
Gerado sucesso: ESTP (index original: 1211)
Gerado sucesso: ENFP (index original: 1212)
Gerado sucesso: ENTP (index original: 1214)
Gerado sucesso: ENTP (index original: 1215)
Gerado sucesso: ISTJ (index original: 1216)
Gerado sucesso: ENTP (index original: 1217)
Gerado sucesso: ESFP (index original: 1218)
Gerado sucesso: ENTP (index original: 1220)
Gerado sucesso: ENFJ (index original: 1221)
Gerado sucesso: ENFP (index original: 1224)
Gerado sucesso: ESFJ (index original: 1227)
Gerado sucesso: ENTP (index original: 1234)
Gerado sucesso: ENFP (index original: 1236)
Gerado sucesso: ISFP (index original: 1239)
Gerado sucesso: ESTJ (index original: 1240)
Gerado sucesso: ENFP (index original: 1242)
Gerado sucesso: ENTJ (index original: 1247)
Gerado sucesso: ENFP (index original: 1248)
Gerado sucesso: ENFJ (index original: 1249)
Gerado sucesso: ISFP (index original: 1251)
Gerado sucesso: ENFP (index original: 1255)
Gerado sucesso: ENTP (index original: 1261)
Gerado sucesso: ENTP (index original: 1264)
Gerado sucesso: ENFP (index original: 1266)
Gerado sucesso: ENTJ (index original: 1267)
Gerado sucesso: ISFJ (index original: 1268)
Gerado sucesso: ENTP (index original: 1278)
Gerado sucesso: ESTP (index original: 1279)
Gerado sucesso: ISTP (index original: 1280)
Gerado sucesso: ENTP (index original: 1281)
Gerado sucesso: ENTP (index original: 1285)
Gerado sucesso: ENTP (index original: 1287)
Gerado sucesso: ISTP (index original: 1290)
Gerado sucesso: ENFP (index original: 1293)
Gerado sucesso: ISTJ (index original: 1294)
Gerado sucesso: ESTP (index original: 1303)
Gerado sucesso: ISFJ (index original: 1306)
Gerado sucesso: ENTP (index original: 1308)
Gerado sucesso: ENTP (index original: 1309)
Gerado sucesso: ENFP (index original: 1312)
Gerado sucesso: ISTJ (index original: 1313)
Gerado sucesso: ISFP (index original: 1319)
Gerado sucesso: ENTP (index original: 1322)
Gerado sucesso: ISTP (index original: 1325)
Gerado sucesso: ENTP (index original: 1326)
Gerado sucesso: ISTP (index original: 1328)
Gerado sucesso: ISTP (index original: 1330)
Gerado sucesso: ENFJ (index original: 1334)
Gerado sucesso: ENFP (index original: 1335)
Gerado sucesso: ENFJ (index original: 1336)
Gerado sucesso: ENTJ (index original: 1339)
Gerado sucesso: ENTJ (index original: 1341)
Gerado sucesso: ISTP (index original: 1344)
Gerado sucesso: ENFP (index original: 1345)
Gerado sucesso: ENFP (index original: 1347)
Gerado sucesso: ISFJ (index original: 1349)
Gerado sucesso: ISTJ (index original: 1361)
Gerado sucesso: ENFP (index original: 1362)
Gerado sucesso: ENTJ (index original: 1364)
Gerado sucesso: ENFP (index original: 1365)
Gerado sucesso: ENFP (index original: 1366)
Gerado sucesso: ENTP (index original: 1367)
Gerado sucesso: ESTJ (index original: 1368)
Gerado sucesso: ISTP (index original: 1374)
Gerado sucesso: ENFP (index original: 1380)
Gerado sucesso: ENFJ (index original: 1385)
Gerado sucesso: ENFP (index original: 1387)
Gerado sucesso: ENTP (index original: 1388)
Gerado sucesso: ISTP (index original: 1389)
Gerado sucesso: ENTJ (index original: 1390)
Gerado sucesso: ENFP (index original: 1392)
Gerado sucesso: ENTP (index original: 1397)
Gerado sucesso: ISFP (index original: 1398)
Gerado sucesso: ISTP (index original: 1402)
Gerado sucesso: ENTP (index original: 1408)
Gerado sucesso: ISTP (index original: 1409)
Gerado sucesso: ISTJ (index original: 1412)
Gerado sucesso: ENFJ (index original: 1415)
Gerado sucesso: ENTP (index original: 1418)
Gerado sucesso: ISFP (index original: 1421)
Gerado sucesso: ENTP (index original: 1428)
Gerado sucesso: ESFP (index original: 1429)
Gerado sucesso: ENTP (index original: 1431)
Gerado sucesso: ENTP (index original: 1432)
Gerado sucesso: ENFP (index original: 1433)
Gerado sucesso: ENFP (index original: 1435)
Gerado sucesso: ENFJ (index original: 1441)
Gerado sucesso: ISFJ (index original: 1446)
Gerado sucesso: ENFJ (index original: 1447)
Gerado sucesso: ESTJ (index original: 1450)
Gerado sucesso: ENFP (index original: 1452)
Gerado sucesso: ENTP (index original: 1454)
Gerado sucesso: ENFP (index original: 1455)
Gerado sucesso: ENTP (index original: 1461)
Gerado sucesso: ENFP (index original: 1462)
Gerado sucesso: ISTJ (index original: 1468)
Gerado sucesso: ISTP (index original: 1471)
Gerado sucesso: ENTJ (index original: 1479)
Gerado sucesso: ISTJ (index original: 1480)
Gerado sucesso: ESTP (index original: 1481)
Gerado sucesso: ISTP (index original: 1485)
Gerado sucesso: ENFP (index original: 1495)
Gerado sucesso: ENTP (index original: 1497)
Gerado sucesso: ISFP (index original: 1498)
Gerado sucesso: ISTJ (index original: 1499)
Gerado sucesso: ISFJ (index original: 1500)
Gerado sucesso: ENFP (index original: 1502)
Gerado sucesso: ISTJ (index original: 1503)
Gerado sucesso: ISFJ (index original: 1507)
Gerado sucesso: ISFJ (index original: 1508)
Gerado sucesso: ESFJ (index original: 1509)
Gerado sucesso: ISTP (index original: 1513)
Gerado sucesso: ENTP (index original: 1515)
Gerado sucesso: ENFP (index original: 1518)
Gerado sucesso: ENTP (index original: 1521)
Gerado sucesso: ENFP (index original: 1524)
Gerado sucesso: ESFP (index original: 1528)
Gerado sucesso: ESTP (index original: 1533)
Gerado sucesso: ISTP (index original: 1534)
Gerado sucesso: ENTP (index original: 1535)
Gerado sucesso: ENTP (index original: 1538)
Gerado sucesso: ISTJ (index original: 1539)
Gerado sucesso: ISTP (index original: 1544)
Gerado sucesso: ENTP (index original: 1552)
Gerado sucesso: ESTJ (index original: 1559)
Gerado sucesso: ISFJ (index original: 1560)
Gerado sucesso: ENTP (index original: 1562)
Gerado sucesso: ISFJ (index original: 1563)
Gerado sucesso: ISTJ (index original: 1564)
Gerado sucesso: ENTP (index original: 1566)
Gerado sucesso: ISTP (index original: 1576)
Gerado sucesso: ISTP (index original: 1579)
Gerado sucesso: ENFP (index original: 1586)
Gerado sucesso: ENFJ (index original: 1587)
Gerado sucesso: ENFP (index original: 1588)
Gerado sucesso: ENFP (index original: 1594)
Gerado sucesso: ENTP (index original: 1604)
Gerado sucesso: ENFP (index original: 1609)
Gerado sucesso: ENTP (index original: 1610)
Gerado sucesso: ENTP (index original: 1612)
Gerado sucesso: ENFP (index original: 1615)
Gerado sucesso: ENTP (index original: 1616)
Gerado sucesso: ENTP (index original: 1621)
Gerado sucesso: ENFJ (index original: 1625)
Gerado sucesso: ENFP (index original: 1627)
Gerado sucesso: ENFP (index original: 1629)
Gerado sucesso: ISTP (index original: 1633)
Gerado sucesso: ISFP (index original: 1636)
Gerado sucesso: ENFP (index original: 1639)
Gerado sucesso: ENFJ (index original: 1640)
Gerado sucesso: ENFP (index original: 1647)
Gerado sucesso: ENFP (index original: 1650)
Gerado sucesso: ENFP (index original: 1651)
Gerado sucesso: ESFJ (index original: 1652)
Gerado sucesso: ENTP (index original: 1659)
Gerado sucesso: ISTJ (index original: 1660)
Gerado sucesso: ENFP (index original: 1667)
Gerado sucesso: ENTP (index original: 1678)
Gerado sucesso: ENFJ (index original: 1679)
Gerado sucesso: ISFP (index original: 1682)
Gerado sucesso: ENTP (index original: 1685)
Gerado sucesso: ISTJ (index original: 1688)
Gerado sucesso: ENFP (index original: 1689)
Gerado sucesso: ISFP (index original: 1693)
Gerado sucesso: ESTJ (index original: 1694)
Gerado sucesso: ENTP (index original: 1697)
Gerado sucesso: ISFJ (index original: 1705)
Gerado sucesso: ENFP (index original: 1711)
Gerado sucesso: ISTP (index original: 1712)
Gerado sucesso: ENFJ (index original: 1713)
Gerado sucesso: ENTP (index original: 1715)
Gerado sucesso: ENFP (index original: 1716)
Gerado sucesso: ESTP (index original: 1719)
Gerado sucesso: ENTP (index original: 1720)
Gerado sucesso: ENTP (index original: 1721)
Gerado sucesso: ENTJ (index original: 1727)
Gerado sucesso: ISFJ (index original: 1728)
Gerado sucesso: ENFJ (index original: 1733)
Gerado sucesso: ISTJ (index original: 1740)
Gerado sucesso: ENTP (index original: 1747)
Gerado sucesso: ENTP (index original: 1748)
Gerado sucesso: ENTJ (index original: 1757)
Gerado sucesso: ISTJ (index original: 1758)
Gerado sucesso: ISFP (index original: 1759)
Gerado sucesso: ENTP (index original: 1762)
Gerado sucesso: ISTJ (index original: 1763)
Gerado sucesso: ISTP (index original: 1765)
Gerado sucesso: ISTJ (index original: 1767)
Gerado sucesso: ISTJ (index original: 1768)
Gerado sucesso: ENFP (index original: 1770)
Gerado sucesso: ENTP (index original: 1774)
Gerado sucesso: ISFJ (index original: 1775)
Gerado sucesso: ISFP (index original: 1778)
Gerado sucesso: ENFP (index original: 1780)
Gerado sucesso: ENTP (index original: 1783)
Gerado sucesso: ENFP (index original: 1784)
Gerado sucesso: ENTJ (index original: 1785)
Gerado sucesso: ENFP (index original: 1789)
Gerado sucesso: ENTJ (index original: 1791)
Gerado sucesso: ISTP (index original: 1803)
Gerado sucesso: ISTP (index original: 1804)
Gerado sucesso: ISTJ (index original: 1807)
Gerado sucesso: ESFJ (index original: 1808)
Gerado sucesso: ISTJ (index original: 1809)
Gerado sucesso: ISTJ (index original: 1811)
Gerado sucesso: ISFJ (index original: 1814)
Gerado sucesso: ISTP (index original: 1816)
Gerado sucesso: ENTP (index original: 1817)
Gerado sucesso: ENTJ (index original: 1819)
Gerado sucesso: ENTP (index original: 1820)
Gerado sucesso: ENTP (index original: 1821)
Gerado sucesso: ENTP (index original: 1824)
Gerado sucesso: ISFP (index original: 1833)
Gerado sucesso: ENFP (index original: 1844)
Gerado sucesso: ENTP (index original: 1845)
Gerado sucesso: ENTP (index original: 1846)
Gerado sucesso: ENTP (index original: 1847)
Gerado sucesso: ENFP (index original: 1853)
Gerado sucesso: ISFP (index original: 1854)
Gerado sucesso: ENFP (index original: 1856)
Gerado sucesso: ISTJ (index original: 1857)
Gerado sucesso: ISTP (index original: 1859)
Gerado sucesso: ISFP (index original: 1860)
Gerado sucesso: ISTJ (index original: 1867)
Gerado sucesso: ENTP (index original: 1868)
Gerado sucesso: ISFJ (index original: 1872)
Gerado sucesso: ISFP (index original: 1874)
Gerado sucesso: ENTP (index original: 1876)
Gerado sucesso: ENTP (index original: 1879)
Gerado sucesso: ENFP (index original: 1880)
Gerado sucesso: ENTP (index original: 1881)
Gerado sucesso: ENTP (index original: 1884)
Gerado sucesso: ISTJ (index original: 1890)
Gerado sucesso: ISTP (index original: 1894)
Gerado sucesso: ENTP (index original: 1896)
Gerado sucesso: ISTJ (index original: 1899)
Gerado sucesso: ENTP (index original: 1900)
Gerado sucesso: ISTJ (index original: 1901)
Gerado sucesso: ENTP (index original: 1903)
Gerado sucesso: ISFP (index original: 1904)
Gerado sucesso: ENFJ (index original: 1905)
Gerado sucesso: ISFP (index original: 1906)
Gerado sucesso: ENTP (index original: 1911)
Gerado sucesso: ENTP (index original: 1913)
Gerado sucesso: ENTJ (index original: 1915)
Gerado sucesso: ESTJ (index original: 1916)
Gerado sucesso: ENTP (index original: 1917)
Gerado sucesso: ESFP (index original: 1923)
Gerado sucesso: ENFP (index original: 1925)
Gerado sucesso: ENTP (index original: 1928)
Gerado sucesso: ISTJ (index original: 1929)
Gerado sucesso: ESFP (index original: 1930)
Gerado sucesso: ISFP (index original: 1931)
Gerado sucesso: ISTP (index original: 1933)
Gerado sucesso: ENFP (index original: 1934)
Gerado sucesso: ENFP (index original: 1939)
Gerado sucesso: ISTP (index original: 1940)
Gerado sucesso: ENTP (index original: 1941)
Gerado sucesso: ESTP (index original: 1946)
Gerado sucesso: ENFP (index original: 1948)
Gerado sucesso: ENTP (index original: 1950)
Gerado sucesso: ENTP (index original: 1951)
Gerado sucesso: ISTP (index original: 1955)
Gerado sucesso: ENTP (index original: 1962)
Gerado sucesso: ENTP (index original: 1966)
Gerado sucesso: ISFP (index original: 1969)
Gerado sucesso: ISFP (index original: 1970)
Gerado sucesso: ENFP (index original: 1972)
Gerado sucesso: ISFP (index original: 1976)
Gerado sucesso: ISTP (index original: 1977)
Gerado sucesso: ENTP (index original: 1978)
Gerado sucesso: ENFP (index original: 1979)
Gerado sucesso: ISTJ (index original: 1981)
Gerado sucesso: ENFJ (index original: 1982)
Gerado sucesso: ISTJ (index original: 1985)
Gerado sucesso: ISTP (index original: 1986)
Gerado sucesso: ENTP (index original: 1987)
Gerado sucesso: ENFJ (index original: 1989)
Gerado sucesso: ENTP (index original: 1991)
Gerado sucesso: ENTP (index original: 2000)
Gerado sucesso: ISFJ (index original: 2007)
Gerado sucesso: ESFP (index original: 2008)
Gerado sucesso: ENTP (index original: 2011)
Gerado sucesso: ISTJ (index original: 2013)
Gerado sucesso: ESFP (index original: 2020)
Gerado sucesso: ENFP (index original: 2021)
Gerado sucesso: ISTP (index original: 2023)
Gerado sucesso: ENTP (index original: 2027)
Gerado sucesso: ISFP (index original: 2028)
Gerado sucesso: ENFP (index original: 2030)
Gerado sucesso: ISTP (index original: 2036)
Gerado sucesso: ENTP (index original: 2038)
Gerado sucesso: ISTP (index original: 2042)
Gerado sucesso: ENTJ (index original: 2043)
Gerado sucesso: ESFJ (index original: 2044)
Gerado sucesso: ENFP (index original: 2057)
Gerado sucesso: ENFP (index original: 2059)
Gerado sucesso: ENFP (index original: 2069)
Gerado sucesso: ISTP (index original: 2075)
Gerado sucesso: ENFP (index original: 2076)
Gerado sucesso: ENFJ (index original: 2079)
Gerado sucesso: ISTJ (index original: 2081)
Gerado sucesso: ISTJ (index original: 2082)
Gerado sucesso: ENTJ (index original: 2083)
Gerado sucesso: ENFP (index original: 2087)
Gerado sucesso: ENFP (index original: 2089)
Gerado sucesso: ENTP (index original: 2092)
Gerado sucesso: ENFP (index original: 2094)
Gerado sucesso: ENTJ (index original: 2100)
Gerado sucesso: ISTP (index original: 2102)
Gerado sucesso: ISFP (index original: 2103)
Gerado sucesso: ESTP (index original: 2105)
Gerado sucesso: ISTP (index original: 2107)
Gerado sucesso: ENTP (index original: 2109)
Gerado sucesso: ENTJ (index original: 2112)
Gerado sucesso: ENFP (index original: 2113)
Gerado sucesso: ESTP (index original: 2114)
Gerado sucesso: ISTP (index original: 2122)
Gerado sucesso: ISFP (index original: 2124)
Gerado sucesso: ISFJ (index original: 2129)
Gerado sucesso: ISFJ (index original: 2131)
Gerado sucesso: ENTP (index original: 2133)
Gerado sucesso: ENTJ (index original: 2135)
Gerado sucesso: ENFP (index original: 2139)
Gerado sucesso: ENTP (index original: 2140)
Gerado sucesso: ENFJ (index original: 2141)
Gerado sucesso: ENFP (index original: 2142)
Gerado sucesso: ISFJ (index original: 2144)
Gerado sucesso: ENTP (index original: 2146)
Gerado sucesso: ISTP (index original: 2147)
Gerado sucesso: ISFP (index original: 2154)
Gerado sucesso: ENTJ (index original: 2155)
Gerado sucesso: ENFJ (index original: 2159)
Gerado sucesso: ENFP (index original: 2161)
Gerado sucesso: ENFJ (index original: 2162)
Gerado sucesso: ENFJ (index original: 2165)
Gerado sucesso: ISFP (index original: 2169)
Gerado sucesso: ISTP (index original: 2171)
Gerado sucesso: ENTJ (index original: 2173)
Gerado sucesso: ESTJ (index original: 2176)
Gerado sucesso: ENFP (index original: 2178)
Gerado sucesso: ESTP (index original: 2181)
Gerado sucesso: ENFP (index original: 2185)
Gerado sucesso: ENFP (index original: 2191)
Gerado sucesso: ENTP (index original: 2193)
Gerado sucesso: ENTP (index original: 2194)
Gerado sucesso: ENTP (index original: 2203)
Gerado sucesso: ISTP (index original: 2204)
Gerado sucesso: ENTP (index original: 2205)
Gerado sucesso: ENTP (index original: 2206)
Gerado sucesso: ENTJ (index original: 2212)
Gerado sucesso: ENTJ (index original: 2213)
Gerado sucesso: ENFP (index original: 2215)
Gerado sucesso: ENFP (index original: 2216)
Gerado sucesso: ENFP (index original: 2217)
Gerado sucesso: ENTP (index original: 2222)
Gerado sucesso: ISTP (index original: 2225)
Gerado sucesso: ENFP (index original: 2227)
Gerado sucesso: ISFP (index original: 2228)
Gerado sucesso: ENTP (index original: 2231)
Gerado sucesso: ISFJ (index original: 2232)
Gerado sucesso: ENFJ (index original: 2233)
Gerado sucesso: ISFJ (index original: 2234)
Gerado sucesso: ISFP (index original: 2235)
Gerado sucesso: ENTP (index original: 2237)
Gerado sucesso: ESTP (index original: 2239)
Gerado sucesso: ENTP (index original: 2243)
Gerado sucesso: ISTJ (index original: 2244)
Gerado sucesso: ENFP (index original: 2245)
Gerado sucesso: ENFP (index original: 2253)
Gerado sucesso: ENFP (index original: 2258)
Gerado sucesso: ENFP (index original: 2260)
Gerado sucesso: ISFJ (index original: 2261)
Gerado sucesso: ISFJ (index original: 2263)
Gerado sucesso: ENFJ (index original: 2264)
Gerado sucesso: ESTJ (index original: 2266)
Gerado sucesso: ESTP (index original: 2267)
Gerado sucesso: ENTJ (index original: 2268)
Gerado sucesso: ENTP (index original: 2269)
Gerado sucesso: ESFJ (index original: 2271)
Gerado sucesso: ENFP (index original: 2274)

KeyboardInterrupt:

In [ ]:
df_aumentado_bruto.to_csv('data/raw_datasets/mbti_1_augmented_qwen.csv')

In [ ]:

# 3. AGORA SIM: Limpeza Pesada em TUDO (textos originais + gerados pela IA)
print("Iniciando a limpeza pesada (NLP)...")
preprocessor_pesado = Preprocessor(texts_column='posts')
df_final_limpo = preprocessor_pesado.preprocess_complete(df_aumentado_bruto)

# Salva o resultado final pronto para o Word2Vec
df_final_limpo.head()

In [ ]:
df_aumentado_bruto[df_aumentado_bruto['is_synthetic'] == True]['posts'].iloc[0]

"I'm experiencing a growing unease due to my own absence in these online interactions.\n\nThe predictability of sexual encounters can be monotonous if they follow the same pattern repeatedly. For instance, my partner and I are currently facing circumstances that necessitate creative adaptations of our usual positions – think cowgirl and missionary – as we strive for variety. The dearth of...|||Giving new meaning to 'Game' theory.\n\nGreetings *ENTP Smile*; a dash of creativity is all it takes. We engage in lively conversations, and they do most of the flirting while I acknowledge their presence with subtle nods and respond with witty remarks and cheeky grins.|||This + Lack of Balance and Hand Eye Coordination.|||My actual IQ score is 127. Online intelligence quizzes are amusing. I consistently score in the 140s or higher. As with previous responses in this thread, I'll reiterate that I don't put stock in IQ tests. Before you dismiss... You know you're an ENTP when you disappear from a site for over a year and a half, only to return and find people still engaging with your ideas and thoughts. You know you're an ENTP when... As someone prone to overthinking, I often cite Sherlock Holmes' wisdom: perhaps, when one possesses unique knowledge and abilities like my own, it naturally inclines them towards seeking complexity...|||So, here's the deal: 400,000+ posts, and yet not exactly; I've never bought into E/I or J/P as genuine faculties. Instead, I gauge myself by what I utilize. My go-to modes are Ne and Ti, with Fe for emotional resonance and occasional Si flashes. Additionally, my Ni is particularly robust...|||You know what? That was cleverly executed. Now that I've said it, I'm genuinely curious to experiment and see how playing a first-person shooter in the backseat while we drive around would pan out. I'd love to observe their reactions...|||Out of all the rock-paper ones, the best one is still the classic. It always leaves me chuckling. You guys are pretty lucky :D I'm rather high up on the Tumblr hierarchy, if I do say so myself.|||So, have you caught wind of that newly released first-person shooter game? I've been thoroughly enjoying the soundtrack on my high-quality sound system, which is capable of producing a truly earth-shaking experience. We managed to set up a few PS3 consoles...|||Actually, the way he linked concepts together was quite characteristic of Ne-dominant personalities. For instance, individuals like Shawn Spencer or Patrick Jane, both ENTPs, tend to be equally attuned to their surroundings as Se-dominant types.|||Honestly, I must confess that I do get a touch jealous, just like you do. I attribute this to the fusion of my 4w3 heart with my dominant 7w8 nature. Both 7s and 8s crave attention, while 4s yearn to be recognized – though not necessarily in the same way...|||;D I'll upload the same clip with the microphone positioned away from my mouth, so you won't pick up any audio. It'll be like a stealthy ninja assassin move, minus the gore.|||Tik Tok is actually a fantastic song. As long as you can mentally filter out the singer's vocals, the beat really gets me moving and grooving.|||drop.io v1swck0 :D My mic's proximity to my mouth is quite intimate, with a game of assassins in the background - smokin' aces, if you will.|||Sociability doesn't equate to extroversion; I'm an extrovert, yet not sociable at all. :)|||Sherlock Holmes, as portrayed in film, was an ENTP; typically, he's played as an EXTJ or ESTJ in adaptations. The movie itself looked great, but the title 'Sherlock Holmes' didn't quite fit.|||http://i817.photobucket.com/albums/zz96/kamioo/Dirtywinch.png|||Fear of kissing a guy never crossed my mind; I'd even kiss an animal if I had to! So, nothing vanished - just personal taste and not being into it. The fellow I kissed didn't know me, making it one of those...|||The conundrum unfolds much like my own introspection, grappling with the multitude of paths to pursue in life. My dilemma stems from the plethora of aspirations, but the biggest hurdle lies in recognizing that inaction would mean missing out on potential opportunities. Meanwhile, a peculiar development has arisen - a gay friend harbors romantic feelings for me, prompting an intense flush. As someone who empathizes with others, I find myself entangled in this predicament, torn between my own desires and the weight of responsibility.|||I'm an intuitive individual, tilting towards the extroverted side. People with similar inclinations to mine - ENTPs and INTPs - tend to resonate with me effortlessly. Besides, I envision their inquisitions would unfold like a mechanical, calculated sequence, much like Jack's from 24, but amplified by a DIY approach using discarded car parts. It's an intended compliment, I assure you! I share some psychopathic tendencies, albeit with a dash of unconventional humor, which manifests as laughter - even when I'm injured or witnessing others' mishaps, like accidentally mowing their lawn...|||I typically stay until the event concludes. Meanwhile, between moments, you're working on your endeavors. I'll be tending to mine. It's a pleasure making your acquaintance.\n\nI should have trusted my instincts; I would've been more accurate earlier. I initially thought INFP might fit the bill.\nEXFP seems a stronger possibility, given her response pattern. My friends, including those in the LGBTQ+ community, often seek my counsel.\nI acknowledge the expertise of my ENTP mentors; without them, I wouldn't have achieved what I'm accomplishing today.\n\nWhat are you insinuating? I never engage in such behavior.|||It's challenging to lament the loss of someone you've grown fond of when you're convinced you were in the right, and you can't help but acknowledge your own exceptional correctness with a self-assured nod. \n\nMany of them might be foolish, I'm aware of that. That's precisely why I find joy in engaging with them, as it often leaves me chuckling. :D As I prepare to pursue Neuropsychology, I've also developed connections with several psychologists...|||:D As a Nightowl, my sleep patterns are quite unique - I typically rise between 6-7 pm and remain awake until the early morning hours of 10-11:30 am.\n\nTheoretically speaking, it would appear that INTPs might struggle socially. While INTJs may be indifferent to social interactions, they will nonetheless utilize these situations when necessary....|||My digital portfolio on my desktop is comprised of personal stock images I've downloaded from various online sources and photobucket sites.|||I'll let you know when I start editing the images. By the way, I'm happy you enjoy the static design. Thanks for your appreciation!\n\n[Links to images]\n\nThis piece was created for a friend, and it took several hours of work. To be exact, every line was carefully crafted by me...\n\n[More links to images]\n\nStatic: [Link to image]\n\nI'll have to get back to your avatar later if one of my teammates beats me to it.\n\nBy the way, psychologists don't keep me around long enough to diagnose me. I actually enjoy playing with them and figuring out their diagnoses for myself. According to my own self-diagnosis, as well as the opinions of a few psychologist friends (and some other friends), what I have diagnosed myself with is..."

In [ ]:

# 3. AGORA SIM: Limpeza Pesada em TUDO (textos originais + gerados pela IA)
print("Iniciando a limpeza pesada (NLP)...")
preprocessor_pesado = Preprocessor(texts_column='posts')
df_final_limpo = preprocessor_pesado.preprocess_complete(df_aumentado_bruto)

# Salva o resultado final pronto para o Word2Vec
df_final_limpo.head()

In [ ]:
df_aumentado.head()

   type                                              posts  is_synthetic
0  INFJ  moment sportscenter top ten play prankswhat ha...         False
1  ENTP  im finding lack post alarmingsex boring positi...         False
2  INTP  good one _____ course say know thats blessing ...         False
3  INTJ  dear enjoyed conversation day esoteric gabbing...         False
4  ENTJ  youre firedthats another silly misconception a...         False