In [3]:
!pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 1.5 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
     |████████████████████████████████| 349 kB 34.1 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/yasmimdantas/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 45.8 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 52.7 MB/s eta 0:00:01
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.3.3 pytz-2026.2 tzdata-2026.2
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [1]:
import pandas as pd 
from pipeline.preprocessor import Preprocessor

ModuleNotFoundError: No module named 'pandas'

In [3]:
preprocessor = Preprocessor('body')

In [4]:
df = pd.read_csv('data/MBTI_5M_version_unclean.csv')

/var/folders/by/fx0cy12x2h3dvj961c5y3cxm0000gn/T/ipykernel_5554/3492637699.py:1: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/MBTI_5M_version_unclean.csv')

In [5]:
df.head()

   Unnamed: 0                                               body  mbti
0           0  Knowing you're in INTJ is a tool for you to us...  INTJ
1           1           You are truly an enlightened mastermind.  INTJ
2           2  You should :) it will help if you have a down ...  INFJ
3           3  I watch a bit of everything (including hentai)...  INTP
4           4  I don't know if I would count this as a pet pe...  INTJ

In [6]:
df = df.dropna()

In [7]:
df.drop(columns = ['Unnamed: 0'], inplace = True)

In [ ]:
preprocessor = Preprocessor('body')

In [ ]:
df_clean = preprocessor.preprocess_simple(df)

In [ ]:
df.head()

                                                body  mbti
0  knowing youre in intj is a tool for you to use...  INTJ
1            you are truly an enlightened mastermind  INTJ
2  you should it will help if you have a down mom...  INFJ
3  i watch a bit of everything including hentai i...  INTP
4  i dont know if i would count this as a pet pee...  INTJ

In [ ]:
df.to_csv('data/clean_datasets/light_cleaning_MBTI_5M.csv')

In [8]:
import gc

gc.collect()

0

In [ ]:
df = pd.read_csv('data/MBTI_5M_version_unclean.csv')

/var/folders/by/fx0cy12x2h3dvj961c5y3cxm0000gn/T/ipykernel_5346/3492637699.py:1: DtypeWarning: Columns (1,2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/MBTI_5M_version_unclean.csv')

In [9]:
df = df.dropna()

In [1]:
import nltk

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/yasmimdantas/nltk_data...

True

In [10]:
df_clean = preprocessor.preprocess_complete(df)

In [15]:
df_clean.head()

                                                body  mbti
0  knowing youre in intj is a tool for you to use...  INTJ
1            you are truly an enlightened mastermind  INTJ
2  you should happyfaceorsmiley it will help if y...  INFJ
3  i watch a bit of everything including hentai i...  INTP
4  i dont know if i would count this a a pet peez...  INTJ

In [18]:
df['body'] = df['body'].apply(remove_stopwords)

In [13]:
df_clean['body'] = df_clean['body'].apply(lambda x: x.lower())

In [19]:
df_clean.head()

                                                body  mbti
0  knowing youre intj tool use interaction people...  INTJ
1                       truly enlightened mastermind  INTJ
2  happyfaceorsmiley help moment hobby keep mind ...  INFJ
3  watch bit everything including hentai tend enj...  INTP
4  dont know would count pet peeze something time...  INTJ

In [20]:
df_clean.to_csv('data/clean_datasets/deep_cleaning_MBTI_5M.csv')

In [21]:
df_clean.head()

                                                body  mbti
0  knowing youre intj tool use interaction people...  INTJ
1                       truly enlightened mastermind  INTJ
2  happyfaceorsmiley help moment hobby keep mind ...  INFJ
3  watch bit everything including hentai tend enj...  INTP
4  dont know would count pet peeze something time...  INTJ